const STORAGE_KEY='picklerate-v3-progress';
const HISTORY_KEY='picklerate-v3-history';
const meta={
 serveIn:['Technical Ability','Serve Consistency','Objective'],serveDepth:['Technical Ability','Serve Quality','Objective'],servePlacement:['Technical Ability','Serve Placement','Objective'],returnIn:['Technical Ability','Return Consistency','Objective'],returnDepth:['Technical Ability','Return Quality','Objective'],returnAdvance:['Technical Ability','Return & Advance','Behaviour'],dropSuccess:['Technical Ability','Third-Shot Drop','Objective'],dropForehand:['Technical Ability','Forehand Drop','Objective'],dropBackhand:['Technical Ability','Backhand Drop','Objective'],dropAdjustment:['Tactical Intelligence','Drop Adaptability','Decision'],driveSelection:['Tactical Intelligence','Third-Shot Selection','Decision'],fifthShot:['Technical Ability','Fifth-Shot Transition','Objective'],dinkCrosscourt:['Technical Ability','Cross-Court Dinking','Objective'],dinkStraight:['Technical Ability','Straight Dinking','Objective'],dinkPlacement:['Tactical Intelligence','Dink Construction','Decision'],dinkPressure:['Technical Ability','Dinking Under Pressure','Objective'],lowBallPatience:['Tactical Intelligence','Attack Patience','Behaviour'],kitchenMovement:['Technical Ability','Kitchen Movement','Objective'],transitionReset:['Technical Ability','Transition Resets','Objective'],blockDrive:['Technical Ability','Drive Blocking','Objective'],backhandBlock:['Technical Ability','Backhand Defence','Objective'],resetAfterPop:['Technical Ability','Defensive Recovery','Objective'],defensiveLob:['Technical Ability','Defensive Lob','Objective'],handsRecovery:['Technical Ability','Hands Recovery','Objective'],speedupSelection:['Tactical Intelligence','Speed-Up Selection','Decision'],speedupExecution:['Technical Ability','Speed-Up Execution','Objective'],counterForehand:['Technical Ability','Forehand Counter','Objective'],counterBackhand:['Technical Ability','Backhand Counter','Objective'],attackTargets:['Tactical Intelligence','Attack Targeting','Decision'],partnerMovement:['Tactical Intelligence','Partner Positioning','Behaviour'],middleCoverage:['Tactical Intelligence','Middle Management','Objective'],targeting:['Tactical Intelligence','Opponent Targeting','Decision'],patternRecognition:['Tactical Intelligence','Pattern Recognition','Decision'],shotTolerance:['Tactical Intelligence','Shot Tolerance','Behaviour'],rallyConsistency:['Competitive Validation','Pressure Execution','Experience'],unforcedErrors:['Technical Ability','Error Control','Objective'],badDayFloor:['Technical Ability','Performance Floor','Behaviour'],adaptPressure:['Tactical Intelligence','In-Match Adaptation','Decision'],versus35:['Competitive Validation','Performance vs 3.5','Experience'],versus40:['Competitive Validation','Performance vs 4.0','Experience'],strongPartner:['Competitive Validation','Stronger-Partner Contribution','Experience'],newPartner:['Competitive Validation','New-Partner Adaptability','Experience'],tournamentTransfer:['Competitive Validation','Tournament Transfer','Experience']};
const pillarWeights={'Technical Ability':.70,'Tactical Intelligence':.20,'Competitive Validation':.10};
const evidenceTrust={Objective:1,Behaviour:.86,Decision:.72,Experience:.62};
const pillarDescriptions={'Technical Ability':'Execution quality across the core shots and movement demands of the game.','Tactical Intelligence':'Shot selection, positioning, patience, targeting and in-match adaptation.','Competitive Validation':'How reliably your game transfers to pressure, stronger opposition and unfamiliar partners.'};
const drills={
 'Third-Shot Drop':['Drop ladder','Hit 10 drops from three depths; only advance after 7 land unattackably.'],
 'Forehand Drop':['Forehand drop targets','Alternate middle and cross-court drops, tracking unattackable balls out of 20.'],
 'Backhand Drop':['Backhand drop block','Play 20 backhand-only third shots, then transition behind every successful drop.'],
 'Fifth-Shot Transition':['3rd–5th progression','Drop, split-step, then reset the fifth shot before advancing.'],
 'Transition Resets':['Transition reset ladder','Start at the baseline and move forward only after two controlled resets.'],
 'Drive Blocking':['Block-to-kitchen','Partner drives 20 balls; score only blocks that bounce in the kitchen.'],
 'Backhand Defence':['Backhand wall blocks','Compact backhand blocks with no backswing; target the kitchen middle.'],
 'Cross-Court Dinking':['Cross-court consistency','Play cooperative-to-competitive dinks and count rallies reaching 10 controlled shots.'],
 'Dinking Under Pressure':['Variable dink feeds','Partner changes depth and pace while you keep 7 of 10 balls unattackable.'],
 'Dink Construction':['Three-ball pattern','Use wide, middle and deep dinks to create a planned fourth-ball opening.'],
 'Speed-Up Selection':['Green-light speed-ups','Only attack balls above a chosen height; lose a point for attacking red-light balls.'],
 'Attack Targeting':['Target windows','Call body, dominant hip or middle before each attack and track execution.'],
 'Partner Positioning':['Two-player shadow movement','Move as a unit through wide balls, transition and recovery without a ball first.'],
 'Pattern Recognition':['Pattern call-out games','After each rally, name the opponent pattern and one possible adjustment.'],
 'Shot Tolerance':['Patience game','A team may only attack after six neutral contacts or a clearly high ball.'],
 'In-Match Adaptation':['Two-error reset','After two similar errors, state and test one specific adjustment.'],
 'Error Control':['Twenty-ball discipline','Play 20 routine balls with margin; restart after an avoidable miss.']
};
let questions=[],answers={},index=0,showAllSkills=false,tester={},currentRecordId=null;
const $=id=>document.getElementById(id);
async function init(){
 try{questions=await fetch('questions.json').then(r=>{if(!r.ok)throw Error();return r.json()})}catch{document.body.innerHTML='<main style="padding:40px;font-family:sans-serif"><h1>Unable to load questions.json</h1><p>Run this folder through a local server.</p></main>';return}
 if(loadProgress()?.answers&&Object.keys(loadProgress().answers).length)$('resumeBtn').classList.remove('hidden');
 bindEvents();
}
function bindEvents(){
 $('startBtn').onclick=()=>openTester(false);$('resumeBtn').onclick=()=>startAssessment(true);$('historyBtn').onclick=showHistory;$('historyHeaderBtn').onclick=showHistory;
 $('skipTesterBtn').onclick=()=>{tester={};startAssessment(false)};$('beginAssessmentBtn').onclick=()=>{tester=readTester();startAssessment(false)};
 $('backBtn').onclick=()=>{if(index>0){index--;renderQuestion()}};$('nextBtn').onclick=nextQuestion;$('saveExitBtn').onclick=saveExit;$('resetHeaderBtn').onclick=resetCurrent;
 $('retakeBtn').onclick=()=>openTester(false);$('downloadBtn').onclick=()=>downloadCurrentJson();$('toggleSkillsBtn').onclick=()=>{showAllSkills=!showAllSkills;$('toggleSkillsBtn').textContent=showAllSkills?'Show fewer':'Show all';renderSkillResults(calculateResults())};
 $('saveFeedbackBtn').onclick=saveFeedback;$('exportHistoryCsvBtn').onclick=exportHistoryCsv;$('exportHistoryJsonBtn').onclick=exportHistoryJson;$('clearHistoryBtn').onclick=clearHistory;$('backToHistoryBtn').onclick=showHistory;
 document.addEventListener('keydown',e=>{if(!$('assessmentView').classList.contains('hidden')&&'12345'.includes(e.key))selectOption(Number(e.key)-1)});
}
function switchView(id){['landingView','testerView','assessmentView','resultsView','historyView','historyDetailView'].forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:'smooth'})}
function openTester(){switchView('testerView');$('resetHeaderBtn').classList.add('hidden')}
function readTester(){return{name:$('testerName').value.trim()||'Anonymous',knownLevel:numOrNull($('knownLevel').value),ratingSource:$('ratingSource').value,yearsPlayed:numOrNull($('yearsPlayed').value),playType:$('playType').value,environment:$('environment').value}}
function numOrNull(v){return v===''?null:Number(v)}
function startAssessment(resume){if(resume){const s=loadProgress();answers=s.answers||{};index=s.index||0;tester=s.tester||{}}else{answers={};index=0;localStorage.removeItem(STORAGE_KEY)}switchView('assessmentView');$('resetHeaderBtn').classList.remove('hidden');renderCategories();renderQuestion()}
function renderCategories(){const cats=[...new Set(questions.map(q=>q.category))];$('categoryList').innerHTML=cats.map(c=>`<div class="category-item" data-cat="${c}"><span class="category-dot"></span><span>${c}</span></div>`).join('')}
function renderQuestion(){const q=questions[index],m=meta[q.id];$('progressText').textContent=`Question ${index+1} of ${questions.length}`;$('progressPercent').textContent=`${Math.round((index+1)/questions.length*100)}%`;$('progressBar').style.width=`${(index+1)/questions.length*100}%`;$('questionCategory').textContent=q.category;$('evidenceChip').textContent=`${m[2]} evidence`;$('questionText').textContent=q.text;$('questionHelp').textContent=q.help||'';$('optionsList').innerHTML=q.options.map((o,i)=>`<button class="option-card ${answers[q.id]===o.score?'selected':''}" data-index="${i}"><span class="option-index">${i+1}</span><span>${o.text}</span></button>`).join('');[...$('optionsList').children].forEach((el,i)=>el.onclick=()=>selectOption(i));$('nextBtn').disabled=!answers[q.id];$('nextBtn').innerHTML=index===questions.length-1?'See my results <span>→</span>':'Next question <span>→</span>';$('backBtn').disabled=index===0;updateCategoryState(q.category);saveProgress()}
function selectOption(i){const q=questions[index];answers[q.id]=q.options[i].score;renderQuestion()}
function nextQuestion(){if(!answers[questions[index].id])return;if(index<questions.length-1){index++;renderQuestion()}else completeAssessment()}
function updateCategoryState(current){document.querySelectorAll('.category-item').forEach(el=>{const qs=questions.filter(q=>q.category===el.dataset.cat);el.classList.toggle('active',el.dataset.cat===current);el.classList.toggle('done',qs.every(q=>answers[q.id]))})}
function saveProgress(){localStorage.setItem(STORAGE_KEY,JSON.stringify({answers,index,tester,updatedAt:Date.now()}));$('autosaveText').textContent='Progress saved'}
function loadProgress(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))}catch{return null}}
function saveExit(){saveProgress();switchView('landingView');$('resumeBtn').classList.remove('hidden')}
function resetCurrent(){localStorage.removeItem(STORAGE_KEY);answers={};index=0;$('resumeBtn').classList.add('hidden');$('resetHeaderBtn').classList.add('hidden');switchView('landingView')}
function weightedAverage(items){const den=items.reduce((s,x)=>s+x.weight,0);return den?items.reduce((s,x)=>s+x.value*x.weight,0)/den:0}
function calculateResults(){const pillarItems={},skillItems={},evidenceCounts={Objective:0,Behaviour:0,Decision:0,Experience:0};questions.forEach(q=>{if(!answers[q.id])return;const [pillar,skill,type]=meta[q.id],value=answers[q.id],weight=(q.weight||1)*evidenceTrust[type];(pillarItems[pillar]??=[]).push({value,weight,id:q.id});(skillItems[skill]??=[]).push({value,weight,id:q.id,pillar});evidenceCounts[type]++});const pillars={};Object.keys(pillarWeights).forEach(p=>pillars[p]=weightedAverage(pillarItems[p]||[]));const skills={};Object.entries(skillItems).forEach(([s,items])=>skills[s]={score:weightedAverage(items),pillar:items[0].pillar,count:items.length});const overall=Object.entries(pillarWeights).reduce((s,[p,w])=>s+(pillars[p]||0)*w,0);const pairs=[['dropSuccess','dropForehand'],['dropSuccess','dropBackhand'],['dinkCrosscourt','dinkPressure'],['blockDrive','backhandBlock'],['speedupSelection','speedupExecution'],['rallyConsistency','unforcedErrors']];let agreement=1;pairs.forEach(([a,b])=>{if(answers[a]&&answers[b])agreement-=Math.min(Math.abs(answers[a]-answers[b]),3)*.045});agreement=Math.max(.55,agreement);const compCoverage=(pillarItems['Competitive Validation']||[]).length/questions.filter(q=>meta[q.id][0]==='Competitive Validation').length;const confidence=Math.round(Math.min(96,Math.max(45,(Object.keys(answers).length/questions.length*.45+agreement*.35+compCoverage*.2)*100)));return{pillars,skills,overall,confidence,evidenceCounts,agreement,compCoverage}}
function ratingLabel(r){if(r<1.8)return'New player';if(r<2.5)return'Developing beginner';if(r<3)return'Improving recreational';if(r<3.5)return'Intermediate';if(r<4)return'Strong intermediate';if(r<4.5)return'Advanced';return'High-level advanced'}
function completeAssessment(){const results=calculateResults(),record={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),createdAt:new Date().toISOString(),tester:{...tester},answers:{...answers},results,questionVersion:'v3-43',feedback:''};const history=getHistory();history.unshift(record);localStorage.setItem(HISTORY_KEY,JSON.stringify(history));localStorage.removeItem(STORAGE_KEY);currentRecordId=record.id;switchView('resultsView');renderResults(results);$('testerFeedback').value=''}
function renderResults(r){$('overallRating').textContent=r.overall.toFixed(2);$('levelLabel').textContent=ratingLabel(r.overall);$('scoreRing').style.background=`conic-gradient(var(--green) ${r.overall/5*360}deg,#e1e8e4 0deg)`;$('confidenceScore').textContent=`${r.confidence}% · ${r.confidence>=85?'High':r.confidence>=70?'Moderate':'Limited'}`;$('confidenceExplanation').textContent=r.confidence>=85?'Your answers are complete and broadly consistent across related evidence.':r.confidence>=70?'The estimate is useful, but additional competitive evidence would strengthen it.':'Treat this as an early estimate; more match evidence will improve it.';$('pillarResults').innerHTML=Object.keys(pillarWeights).map(p=>`<div class="pillar-row"><header><span class="pillar-icon">●</span><strong>${p}</strong></header><b>${r.pillars[p].toFixed(2)}</b><div class="bar-track"><div class="bar-fill" style="width:${r.pillars[p]/5*100}%"></div></div><p>${Math.round(pillarWeights[p]*100)}% of rating · ${pillarDescriptions[p]}</p></div>`).join('');renderSkillResults(r);renderInsights(r);renderEvidence(r)}
function renderSkillResults(r){const list=Object.entries(r.skills).sort((a,b)=>b[1].score-a[1].score),shown=showAllSkills?list:list.slice(0,10);$('skillResults').innerHTML=shown.map(([n,d])=>`<div class="skill-item"><span>${n}</span><b>${d.score.toFixed(1)}</b><div class="bar-track"><div class="bar-fill" style="width:${d.score/5*100}%"></div></div></div>`).join('')}
function renderInsights(r){const list=Object.entries(r.skills).sort((a,b)=>b[1].score-a[1].score),weak=[...list].reverse();$('strengthsList').innerHTML=list.slice(0,3).map(([n,d],i)=>insight(i+1,n,`A ${d.score.toFixed(1)}/5 score supported by ${d.count} evidence item${d.count===1?'':'s'}.`)).join('');$('weaknessesList').innerHTML=weak.slice(0,3).map(([n,d],i)=>insight(i+1,n,explainWeakness(n,d.score))).join('')}
function insight(i,n,p){return`<div class="insight-item"><span class="insight-number">${i}</span><div><b>${n}</b><p>${p}</p></div></div>`}
function explainWeakness(n,s){const d=drills[n];return d?`${d[1]} Recommended drill: ${d[0]}.`:`At ${s.toFixed(1)}/5, this is one of the clearest opportunities to raise your level.`}
function renderEvidence(r){const total=Object.values(r.evidenceCounts).reduce((a,b)=>a+b,0);$('evidenceSummary').innerHTML=`<div class="evidence-stat"><strong>${total}/${questions.length}</strong><span>Questions completed</span></div><div class="evidence-stat"><strong>${Math.round(r.agreement*100)}%</strong><span>Related-answer agreement</span></div><div class="evidence-stat"><strong>${Math.round(r.compCoverage*100)}%</strong><span>Competitive evidence coverage</span></div>`}
function getHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY))||[]}catch{return[]}}
function showHistory(){switchView('historyView');$('resetHeaderBtn').classList.add('hidden');renderHistory()}
function renderHistory(){const h=getHistory();if(!h.length){$('historySummary').innerHTML='';$('historyList').innerHTML='<div class="empty-history detail-card"><h2>No completed assessments yet</h2><p>Your completed PickleRate profiles will appear here.</p></div>';return}const latest=h[0],best=Math.max(...h.map(x=>x.results.overall)),avg=h.reduce((s,x)=>s+x.results.overall,0)/h.length,change=h.length>1?latest.results.overall-h[h.length-1].results.overall:0;$('historySummary').innerHTML=stat(h.length,'Assessments')+stat(latest.results.overall.toFixed(2),'Latest rating')+stat(best.toFixed(2),'Highest rating')+stat(`${change>=0?'+':''}${change.toFixed(2)}`,'Overall change');$('historyList').innerHTML=h.map(r=>`<article class="history-card" data-id="${r.id}"><div class="history-card-top"><div><span class="history-card-meta">${formatDate(r.createdAt)}</span><h3>${escapeHtml(r.tester?.name||'Anonymous')}</h3><div class="history-card-meta">${r.tester?.knownLevel?`Known level ${r.tester.knownLevel} · `:''}${escapeHtml(r.tester?.playType||'Player assessment')}</div></div><div><div class="history-rating">${r.results.overall.toFixed(2)}</div><span class="confidence-pill">${r.results.confidence}% confidence</span></div></div><div class="history-pillars">${Object.entries(r.results.pillars).map(([p,s])=>`<div><small>${p} · ${s.toFixed(2)}</small><div class="tiny-bar"><i style="width:${s/5*100}%"></i></div></div>`).join('')}</div><div class="history-card-footer"><span>${ratingLabel(r.results.overall)}</span><b>Open full result →</b></div></article>`).join('');document.querySelectorAll('.history-card').forEach(c=>c.onclick=()=>showHistoryDetail(c.dataset.id))}
function stat(v,l){return`<div class="history-stat"><strong>${v}</strong><span>${l}</span></div>`}
function showHistoryDetail(id){const r=getHistory().find(x=>x.id===id);if(!r)return;currentRecordId=id;switchView('historyDetailView');const skills=Object.entries(r.results.skills).sort((a,b)=>b[1].score-a[1].score),weak=[...skills].reverse().slice(0,4);$('historyDetail').innerHTML=`<div class="detail-hero"><article class="detail-card"><span class="eyebrow">ESTIMATED LEVEL</span><div class="detail-rating">${r.results.overall.toFixed(2)}</div><h2>${ratingLabel(r.results.overall)}</h2><p>${r.results.confidence}% confidence · ${formatDate(r.createdAt)}</p></article><article class="detail-card"><span class="eyebrow">TESTER PROFILE</span><h2>${escapeHtml(r.tester?.name||'Anonymous')}</h2><p>${profileText(r.tester)}</p>${r.feedback?`<h3>Feedback</h3><p>${escapeHtml(r.feedback)}</p>`:''}</article></div><div class="detail-grid"><article class="detail-card"><h2>Pillar graph</h2><div class="chart-list">${chartRows(r.results.pillars)}</div><p>Technical execution drives most of the rating. Tactical and competitive evidence refine and validate it.</p></article><article class="detail-card"><h2>Skill graph</h2><div class="chart-list">${chartRows(Object.fromEntries(skills.slice(0,10).map(([n,d])=>[n,d.score])))}</div></article><article class="detail-card"><h2>Recommended drills</h2><div class="drill-list">${weak.map(([n,d])=>drillHtml(n,d.score)).join('')}</div></article><article class="detail-card"><h2>Assessment explanation</h2><p>${historyExplanation(r)}</p><p><b>Evidence agreement:</b> ${Math.round(r.results.agreement*100)}%. <b>Competitive coverage:</b> ${Math.round(r.results.compCoverage*100)}%.</p></article></div><article class="detail-card"><h2>Original answers</h2><div class="answer-list">${questions.map(q=>answerHtml(q,r.answers[q.id])).join('')}</div></article><div class="results-actions"><button class="secondary-btn" onclick="deleteRecord('${r.id}')">Delete this result</button><button class="primary-btn" onclick="downloadRecord('${r.id}')">Download JSON ↓</button></div>`}
function chartRows(obj){return Object.entries(obj).map(([n,v])=>`<div class="chart-row"><span>${n}</span><div class="chart-track"><div class="chart-fill" style="width:${v/5*100}%"></div></div><b>${v.toFixed(2)}</b></div>`).join('')}
function drillHtml(n,s){const d=drills[n]||['Focused repetition',`Use a 10-ball test for ${n.toLowerCase()} and aim to improve from ${Math.round(s*2)}/10 to ${Math.min(10,Math.round(s*2)+2)}/10.`];return`<div class="drill"><h4>${d[0]}</h4><p><b>${n} · ${s.toFixed(1)}/5</b></p><p>${d[1]}</p></div>`}
function answerHtml(q,score){const opt=q.options.find(o=>o.score===score);return`<div class="answer-item"><header><b>${q.text}</b><span>${score||'—'}/5</span></header><p>${opt?escapeHtml(opt.text):'No answer recorded'}</p></div>`}
function historyExplanation(r){const p=r.results.pillars,top=Object.entries(p).sort((a,b)=>b[1]-a[1])[0],low=Object.entries(p).sort((a,b)=>a[1]-b[1])[0];return`This result was led by ${top[0].toLowerCase()} (${top[1].toFixed(2)}). ${low[0]} was the lowest pillar (${low[1].toFixed(2)}), so improvements there may make the player profile more complete. Competitive evidence remains a validator rather than the main driver of the estimated level.`}
function profileText(t={}){return[`Known level: ${t.knownLevel??'not provided'}`,`Source: ${t.ratingSource||'not provided'}`,`Years played: ${t.yearsPlayed??'not provided'}`,t.playType||'Play type not provided',t.environment||'Environment not provided'].join(' · ')}
function saveFeedback(){const h=getHistory(),r=h.find(x=>x.id===currentRecordId);if(!r)return;r.feedback=$('testerFeedback').value.trim();localStorage.setItem(HISTORY_KEY,JSON.stringify(h));$('saveFeedbackBtn').textContent='Saved ✓';setTimeout(()=>$('saveFeedbackBtn').textContent='Save feedback',1200)}
function exportHistoryJson(){downloadBlob(JSON.stringify(getHistory(),null,2),'PickleRate-history.json','application/json')}
function exportHistoryCsv(){const h=getHistory(),heads=['date','tester','known_level','rating_source','years_played','play_type','environment','estimated_rating','technical','tactical','competitive','confidence','feedback'],rows=h.map(r=>[r.createdAt,r.tester?.name||'',r.tester?.knownLevel??'',r.tester?.ratingSource||'',r.tester?.yearsPlayed??'',r.tester?.playType||'',r.tester?.environment||'',r.results.overall.toFixed(2),r.results.pillars['Technical Ability'].toFixed(2),r.results.pillars['Tactical Intelligence'].toFixed(2),r.results.pillars['Competitive Validation'].toFixed(2),r.results.confidence,r.feedback||'']);downloadBlob([heads,...rows].map(row=>row.map(csvCell).join(',')).join('\n'),'PickleRate-history.csv','text/csv')}
function csvCell(v){return`"${String(v).replaceAll('"','""')}"`}
function clearHistory(){if(confirm('Delete all saved assessment history?')){localStorage.removeItem(HISTORY_KEY);renderHistory()}}
function deleteRecord(id){if(!confirm('Delete this saved result?'))return;localStorage.setItem(HISTORY_KEY,JSON.stringify(getHistory().filter(x=>x.id!==id)));showHistory()}
function downloadRecord(id){const r=getHistory().find(x=>x.id===id);if(r)downloadBlob(JSON.stringify(r,null,2),`PickleRate-${r.createdAt.slice(0,10)}.json`,'application/json')}
function downloadCurrentJson(){downloadRecord(currentRecordId)}
function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function formatDate(v){return new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
window.deleteRecord=deleteRecord;window.downloadRecord=downloadRecord;
init();

// App-style routing, navigation and long-term insights.
const APP_VIEWS=['landingView','testerView','assessmentView','resultsView','historyView','historyDetailView','insightsView','aboutView'];
let suppressRoutePush=false;
const originalSwitchView=switchView;
switchView=function(id){
  APP_VIEWS.forEach(v=>{const el=$(v);if(el)el.classList.toggle('hidden',v!==id)});
  document.body.dataset.view=id;
  document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===id||(id==='historyDetailView'&&el.dataset.route==='historyView')));
  document.querySelector('.main-nav')?.classList.remove('open');
  if(id==='insightsView')renderJourneyInsights();
  if(!suppressRoutePush){const hash=viewToHash(id);if(location.hash!==hash)history.pushState({view:id},'',hash)}
  suppressRoutePush=false;
  window.scrollTo({top:0,behavior:'smooth'});
};
function viewToHash(id){return({landingView:'#home',testerView:'#tester',assessmentView:'#assessment',resultsView:'#results',historyView:'#journey',historyDetailView:'#journey-detail',insightsView:'#insights',aboutView:'#about'})[id]||'#home'}
function hashToView(){return({'#home':'landingView','#tester':'testerView','#assessment':'assessmentView','#results':'resultsView','#journey':'historyView','#journey-detail':'historyDetailView','#insights':'insightsView','#about':'aboutView'})[location.hash]||'landingView'}
function routeTo(id){
  if(id==='historyView'){showHistory();return}
  if(id==='historyDetailView'&&currentRecordId){showHistoryDetail(currentRecordId);return}
  switchView(id);
  $('resetHeaderBtn')?.classList.toggle('hidden',id!=='assessmentView');
}
function setupAppNavigation(){
  document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();routeTo(el.dataset.route)}));
  document.querySelectorAll('[data-action="start"]').forEach(el=>el.addEventListener('click',()=>openTester(false)));
  $('mobileMenuBtn')?.addEventListener('click',()=>document.querySelector('.main-nav')?.classList.toggle('open'));
  window.addEventListener('popstate',()=>{suppressRoutePush=true;routeTo(hashToView())});
  if(location.hash&&location.hash!=='#home'){suppressRoutePush=true;routeTo(hashToView())}else history.replaceState({view:'landingView'},'','#home');
}
function renderJourneyInsights(){
  const h=[...getHistory()].reverse(),host=$('journeyInsights');
  if(!host)return;
  if(!h.length){host.innerHTML='<article class="detail-card empty-insights"><h2>Your insights will grow with you</h2><p>Complete your first assessment to establish a baseline. After two or more assessments, PickleRate will show rating trends and skill changes.</p><button class="primary-btn" onclick="openTester(false)">Start assessment →</button></article>';return}
  const latest=h[h.length-1],first=h[0],delta=latest.results.overall-first.results.overall;
  const allSkillNames=[...new Set(h.flatMap(r=>Object.keys(r.results.skills||{})))];
  const changes=allSkillNames.map(name=>{const a=first.results.skills?.[name]?.score,b=latest.results.skills?.[name]?.score;return a==null||b==null?null:{name,change:b-a,current:b}}).filter(Boolean).sort((a,b)=>b.change-a.change);
  const strongest=Object.entries(latest.results.skills||{}).sort((a,b)=>b[1].score-a[1].score).slice(0,4);
  const priorities=Object.entries(latest.results.skills||{}).sort((a,b)=>a[1].score-b[1].score).slice(0,4);
  host.innerHTML=`<div class="history-summary">${stat(h.length,'Assessments')}${stat(latest.results.overall.toFixed(2),'Current rating')}${stat(`${delta>=0?'+':''}${delta.toFixed(2)}`,'Rating change')}${stat(`${latest.results.confidence}%`,'Current confidence')}</div>
  <div class="insights-grid">
    <article class="detail-card wide"><span class="eyebrow">RATING TREND</span><h2>Your assessment timeline</h2><div class="trend-line">${h.map((r,i)=>`<div class="trend-column"><b>${r.results.overall.toFixed(2)}</b><div class="trend-bar" style="height:${Math.max(12,r.results.overall/5*150)}px"></div><small>${new Date(r.createdAt).toLocaleDateString('en-ZA',{day:'numeric',month:'short'})}</small></div>`).join('')}</div></article>
    <article class="detail-card"><span class="eyebrow">CURRENT STRENGTHS</span><h2>What is supporting your level</h2><div class="chart-list">${chartRows(Object.fromEntries(strongest.map(([n,d])=>[n,d.score])))}</div></article>
    <article class="detail-card"><span class="eyebrow">NEXT FOCUS</span><h2>Highest-return practice areas</h2><div class="drill-list">${priorities.map(([n,d])=>drillHtml(n,d.score)).join('')}</div></article>
    <article class="detail-card"><span class="eyebrow">MOST IMPROVED</span><h2>Changes from your baseline</h2>${h.length<2?'<p>Complete another assessment after a period of focused practice to unlock comparisons.</p>':`<div class="chart-list">${changes.slice(0,5).map(x=>`<div class="chart-row"><span>${x.name}</span><div class="chart-track"><div class="chart-fill" style="width:${Math.max(4,x.current/5*100)}%"></div></div><b>${x.change>=0?'+':''}${x.change.toFixed(2)}</b></div>`).join('')}</div>`}</article>
    <article class="detail-card"><span class="eyebrow">CONSISTENT LIMITERS</span><h2>Skills to revisit regularly</h2><p>${priorities.map(([n])=>n).join(', ')} currently sit lowest in your latest profile. Use the suggested drills, then reassess after enough match play to judge whether the improvement transfers.</p></article>
  </div>`;
}
const originalShowHistoryDetail=showHistoryDetail;
showHistoryDetail=function(id){originalShowHistoryDetail(id);history.replaceState({view:'historyDetailView',id},'',`#journey-detail`)};
window.openTester=openTester;
setupAppNavigation();
